title: Site
sections:
  Users:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: huge
    reports:
      - label: Total Users
        value: €29,682
      - label: Paying Users
        value: 265
        info: 12.5%
  Bookmarks:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: medium
    reports:
      - label: Total Bookmarks
        value: 365
      - label: Total Tags
        value: 156

